### ISSUE TITLE
About this game file format

### ISSUE THREAD

**Issue by marcussacana** [jonko0493/Jewelpet-Mahou-no-Oheya-Editor#1]
I want know if you can share any explanation about this game file format.
I found a game with similar signature in their files (but without compression)
![image](https://user-images.githubusercontent.com/10576957/141922245-e0824a60-e70e-483e-a328-a121e23a1c4f.png)
As you can see TBB1 and MTBL, but the main difference here is how the file is decompressed and are using UTF16 as encoding
![image](https://user-images.githubusercontent.com/10576957/141922297-72a26247-4cfb-4688-b431-974334a6ceeb.png)
By what I take a look in your code, your game uses a custom encoding then the tool is incompatible if I just jump the decompression showing invalid string tables like this:
![image](https://user-images.githubusercontent.com/10576957/141922392-bb419b22-71b5-46e4-bcf9-b6491dac2904.png)
Anyway, since my game is a PS4 game is hard to debug directly, If possible you can share what you know about this format?

**Comment by jonko0493** [comment]
Hi! This is super interesting and I'd be happy to help you out. What's the name of the game?

You should be able to rewrite the message parsing method to work on UTF-16 pretty easily which will at least let you view the actual text. From your two screenshots, the format looks nearly identical otherwise, so my guess is that doing that would get you a lot closer to "just working," altho there obviously are likely some differences.

If you'd like to chat more, feel free to send me a message on discord; my handle is Jonko# 0493.
